blank_issues_enabled: true

contact_links:
  - name: ğŸ’¬ Discussions gÃ©nÃ©rales
    url: https://github.com/agentcobra/jdr/discussions
    about: Pour parler du projet, poser des questions ou proposer des idÃ©es informelles.

issue_template_order:
  - 01_proposition_ressource.yml
  - 02_mise_a_jour.yml
  - 03_suggestion_generale.yml
  - 04_bug_technique.yml
